version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  apm-server:
    image: elastic/apm-server:8.17.3
    container_name: apm-server
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200  # Point APM Server to Elasticsearch service
      - APMPROTOCOL=http
    ports:
      - "8200:8200"  # Exposes APM Server API
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  elastic-data:
    driver: local
    driver_opts:
      type: none
      device: D:\Programs\Docker\Volumes\elastic
      o: bind

networks:
  elastic:
